name: AtaAkjemal
description: Bagtly toy!

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.5
  show_up_animation: ^2.0.0
  url_launcher: ^6.1.10

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/image/

  fonts:
    - family: PoiretOne
      fonts:
        - asset: assets/font/PoiretOne-Regular.ttf
    - family: Breathing
      fonts:
        - asset: assets/font/Breathing.ttf
    - family: Pacifico
      fonts:
        - asset: assets/font/Pacifico-Regular.ttf