import 'package:get/get.dart';

class Localization extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en_US': {
          'mainText': 'Wedding Invitation',
          'dateTime': '28.04.23 | Friday | 18:00',
          'location': '"Toÿ Mekany" Small hall, Türkmenbaśy Śaÿoly',
          'g': 'A',
          'b': 'E',
          'young': 'Ata\n&\nEnesh',
          'mainText2': 'We invite you to be a special guest at our wedding on the happiest day!',
          'contact': 'Contact:',
          'email': 'Email: toychakylyklary@gmail.com',
          'tel': 'Phone: (+993 63) 581010',
          'copied': 'Copied',

          //name
          'vladimir': 'Dear Vladimir!',
          'gulnar': 'Dear Gulnar!',
          'vitaliy': 'Dear Vitaliy!',
          'dasha': 'Dear Dasha!',
          'anna': 'Dear Anna!',
          'maral': 'Dear Maral!',
          'lena': 'Dear Lena!',
          'aynabat': 'Dear Aynabat!',
          'ruslan': 'Dear Ruslan!',
          'mekan': 'Dear Mekan!',
          'arslan': 'Dear Arslan!',
          'сhristina': 'Dear Christina!',
          'ania': 'Dear Anya!',
          'oksana': 'Dear Oksana!', //2x
          'guncha': 'Dear Guncha!', //2x
          'jemal': 'Dear Jemal!',
          'bibi': 'Dear Bibi!',
          'atash': 'Dear Atash!',
          'guvanch': 'Dear Guvanch!',
          'hudayberdi': 'Dear Hudayberdi!',
          'katya': 'Dear Katya!',
          'mahym': 'Dear Mahym!',
          'shirin': 'Dear Shirin!',
          'tavus': 'Dear Tavus!',
          'yazmurad': 'Dear Yazmurad!',
          'lyalya': 'Dear Lyale!',
          'serdar': 'Dear Serdar!',
          'aykhan': 'Dear Aykhan!',
          'olya': 'Dear Olya!',
          'muhammet': 'Dear Muhammet!',
          'atajan': 'Dear Atajan!',
          'daria': 'Dear Daria!',
          'gozel': 'Dear Gozel!',

          'didar': 'Dear Didar!',
          'bayram': 'Dear Bayram!',
          'esen': 'Dear Esen!',
          'khoshgeldi': 'Dear Khoshgeldi!',
        },
        'ru_RU': {
          'mainText': 'Приглашение на\n свадьбу',
          'dateTime': '28.04.23 | Пятница | 18:00',
          'location': '"Toÿ Mekany" Малый зал, Türkmenbaśy Śaÿoly ',
          'g': 'А',
          'b': 'Э',
          'young': 'Ата\n&\nЭнеш',
          'mainText2':
              'Приглашаем вас стать желанным гостем на нашей свадьбе в самый счастливый день!',
          'contact': 'Контакты:',
          'saveDate': 'Сохранить дату',
          'email': 'Email: toychakylyklary@gmail.com',
          'tel': 'Телефон: (+993 63) 581010',
          'copied': 'Скопировано',

          //name
          'vladimir': 'Уважаемый Владимир!',
          'gulnar': 'Уважаемая Гульнар!',
          'vitaliy': 'Уважаемый Виталий!',
          'dasha': 'Уважаемая Даша!',
          'anna': 'Уважаемая Анна!',
          'maral': 'Уважаемая Марал!',
          'lena': 'Уважаемая Лена!',
          'aynabat': 'Уважаемая Айнабат!',
          'ruslan': 'Уважаемый Руслан!',
          'mekan': 'Уважаемый Мекан!',
          'arslan': 'Уважаемый Арслан!',
          'сhristina': 'Уважаемая Кристина!',
          'ania': 'Уважаемая Аня!',
          'oksana': 'Уважаемая Оксана!', //2x
          'guncha': 'Уважаемая Гунча!', //2x
          'bibi': 'Уважаемая Биби!',
          'jemal': 'Уважаемая Джемал!',
          'atash': 'Уважаемый Аташ!',
          'guvanch': 'Уважаемый Гуванч!',
          'hudayberdi': 'Уважаемый Худайберди!',
          'katya': 'Уважаемая Катя!',
          'mahym': 'Уважаемая Махым!',
          'shirin': 'Уважаемая Ширин!',
          'tavus': 'Уважаемая Тавус!',
          'yazmurad': 'Уважаемый Язмурад!',
          'lyalya': 'Уважаемая Ляле!',
          'serdar': 'Уважаемый Сердар!',
          'aykhan': 'Уважаемый Айхан!',
          'olya': 'Уважаемая Оля!',
          'muhammet': 'Уважаемый Мухаммед!',
          'atajan': 'Уважаемый Атаджан!',
          'daria': 'Уважаемая Дария!',
          'gozel': 'Уважаемая Гозел!',

          'didar': 'Уважаемый Дидар!',
          'esen': 'Уважаемый Эсен!',
          'khoshgeldi': 'Уважаемый Хошгелди!',
          'bayram': 'Уважаемый Байрам!',
        },
        'tkm_TKM': {
          'mainText': 'Toÿ Çakylygy',
          'dateTime': '28.04.23 | Anna | 18:00',
          'location': '"Toÿ Mekany" kiçi zal, Türkmenbaśy Śaÿoly',
          'g': 'A',
          'b': 'E',
          'young': 'Ata\n&\nEneś',
          'mainText2':
              'Biz Sizi iñ bagtly günümiziñ bolan nika toÿumyzyñ arzyly myhmany bolmaklygyñyza çagyrÿarys!',
          'contact': 'Habarlaśmak üçin:',
          'email': 'Email: toychakylyklary@gmail.com',
          'tel': 'Telefon: (+993 63) 581010',
          'copied': 'Göçürildi',

          //names
          'vladimir': 'Hormatly Wladimir!',
          'gulnar': 'Hormatly Gülnar!',
          'vitaliy': 'Hormatly Witaliÿ!',
          'dasha': 'Hormatly Daśa!',
          'anna': 'Hormatly Anna!',
          'maral': 'Hormatly Maral!',
          'lena': 'Hormatly Lena!',
          'aynabat': 'Hormatly Aÿnabat!',
          'ruslan': 'Hormatly Ruslan!',
          'mekan': 'Hormatly Mekan!',
          'arslan': 'Hormatly Arslan!',
          'сhristina': 'Hormatly Kristina!',
          'ania': 'Hormatly Anÿa!',
          'oksana': 'Hormatly Oksana!', //2x
          'guncha': 'Hormatly Gunça!', //2x
          'jemal': 'Hormatly Jemal!',
          'bibi': 'Hormatly Bibi!',
          'atash': 'Hormatly Ataś!',
          'guvanch': 'Hormatly Guwanç!',
          'hudayberdi': 'Hormatly Hudaÿberdi!',
          'katya': 'Hormatly Katÿa!',
          'mahym': 'Hormatly Mahym!',
          'shirin': 'Hormatly Śirin!',
          'tavus': 'Hormatly Tawus!',
          'yazmurad': 'Hormatly Ÿazmyrat!',
          'lyalya': 'Hormatly Läle!',
          'serdar': 'Hormatly Serdar!',
          'aykhan': 'Hormatly Aykhan!',
          'olya': 'Hormatly Olya!',
          'muhammet': 'Hormatly Muhammet!',
          'atajan': 'Hormatly Atajan!',
          'daria': 'Hormatly Daria!',
          'gozel': 'Hormatly Gözel!',

          'didar': 'Hormatly Didar!',
          'esen': 'Hormatly Esen!',
          'khoshgeldi': 'Hormatly Hośgeldi!',
          'bayram': 'Hormatly Baÿram!',
        }
      };
}
